<?xml version="1.0" encoding="utf-8"?><Database Name="DonorDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DonorDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DonorDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.donordata" Member="donordatas">
    <Type Name="donordata">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="bloodtype" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="phNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>